# version: 2
# updates:
#   - package-ecosystem: "pub"
#     directory: "/"
#     schedule:
#       interval: "daily"
#     allow:
#       - dependency-name: "*"
#     commit-message:
#       prefix: "build: "
#       include: "scope"
#     open-pull-requests-limit: 3
#   - package-ecosystem: "github-actions"
#     directory: "/"
#     schedule:
#       interval: "daily"
#     allow:
#       - dependency-name: "*"
#     commit-message:
#       prefix: "build: "
#       include: "scope"
