name: Deploy test to Android play store
on:
  workflow_dispatch:
    inputs:
     environment:
        type: environment
        description: Select the environment

jobs:
  deploy_playstore_internal:
    environment: 
      name: ${{ inputs.environment }}
    env:
      WEB_APP_ENV: ${{ vars.WEB_APP_ENV }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cat .github/workflows/versions.env >> $GITHUB_ENV
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'zulu'
      - name: Update env files to selected environment
        run: |
          rm .env
          rm assets/.env
          echo "$WEB_APP_ENV"